### ISSUE TITLE
Frame Import not working

### ISSUE THREAD

**Issue by SuckyTheClown** [joshbirnholz/cardconjurer#13]
Issues with card imports not importing any frame elements on google chrome. Attempted to clear cookies, tried on incognito, nothing seems to make this work right. Multiple examples attatched
![image](https://github.com/joshbirnholz/cardconjurer/assets/59133856/30351804-3479-4d08-9d6e-1f9c805a0d0d)

![Capture](https://github.com/joshbirnholz/cardconjurer/assets/59133856/0c2da3f7-5b6a-489b-8710-0abbcb011917)

**Comment by joshbirnholz** [comment]
In your first screenshot, I can see that "Automatically update frame" is set to disabled. In order for frame elements to load automatically, you need to set which frame you want to use there. If this is disabled, frames won't be set for you.
