### ISSUE TITLE
No Multicolor Option for the Dossier Frame

### ISSUE THREAD

**Issue by PippoChiri** [joshbirnholz/cardconjurer#15]
![image](https://github.com/joshbirnholz/cardconjurer/assets/159478868/c46011ce-b242-4958-a8af-6986c4f1582e)
![image](https://github.com/joshbirnholz/cardconjurer/assets/159478868/d1f9354f-b305-4b15-86c3-a20f994b7ff0)

There is no option to make gold cards for the dossier frames like Niv-Mizzet, Guildpact

**Comment by joshbirnholz** [comment]
Fixed in 7180928
