### ISSUE TITLE
No Retroframe options

### ISSUE THREAD

**Issue by sereneking** [joshbirnholz/cardconjurer#18]
Looking through the menu for frames other than Standard, no BRO retro frame treatments seem to exist for all the colors.

**Comment by joshbirnholz** [comment]
What do you mean? Retro frames exist, can you give some examples of what should be there that's missing?

**Comment by sereneking** [comment]
I guess the better question is what frame drop down are the retro frames? I cannot seem to find one. Take for example the retro frame Sol Ring or the retro frame Cursed Mirror?

**Comment by sereneking** [comment]
I guess a better point is, is there a frame dropdown for the updated retro frames from BRO? Since they are not labeled with the set code like other showcase like frame drop down options.

**Comment by joshbirnholz** [comment]
Old/Misc -> Seventh Edition.

They are not a showcase frame and they are not from BRO, so you won’t find them categorized that way.
