### ISSUE TITLE
Importing DFCs no longer works properly

### ISSUE THREAD

**Issue by invalidCards** [joshbirnholz/cardconjurer#22]
Commit https://github.com/joshbirnholz/cardconjurer/commit/18e6fd7f0fb1569ded3fd1ea5f2d3d9d4edb75c3 broke fetching DFCs because of the check on the `keywords` property, which only exists on the full card object, and not on the face objects that the relevant functionality is based on. This results in half-imported data and some weird behaviour with the card view until any field is manually updated.

**Comment by joshbirnholz** [comment]
Fixed with b5d7d7b
