### ISSUE TITLE
No serialized number box frame option

### ISSUE THREAD

**Issue by glitgh-gd** [joshbirnholz/cardconjurer#23]
There is no option to add a serialized number box to a card and to edit the numbers on it

Examples:
<img width="400" alt="Screenshot 2024-05-02 at 9 33 18 PM" src="https://github.com/joshbirnholz/cardconjurer/assets/99004306/6a3d7cb8-ec57-49ae-9c33-aa581502a425">
<img width="445" alt="Screenshot 2024-05-02 at 9 34 42 PM" src="https://github.com/joshbirnholz/cardconjurer/assets/99004306/4242ec49-f969-4cad-8432-68ce66ae6ff8">

**Comment by joshbirnholz** [comment]
Added with commit 65720d4!
